# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Golfo Vasiliou"
description: > # this means to ignore newlines until "email:"
   Web Developer from Greece

email: a-mail@mail.mail
#blog logo
logo: "https://avatars2.githubusercontent.com/u/11340303?v=3&s=460"
# blog cover
cover: "/assets/images/photo-1454165205744-3b78555e5572.jpg"

name: 'Golfo Vasiliou'
author: 'Golfo Vasiliou'
author_image: "https://avatars2.githubusercontent.com/u/11340303?v=3&s=460"


paginate:	5

google_analytics: UA-72072834-2

url: "http://faysvas.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: ''

#fill in disqus shortname to use disqus
disqus: faysvas

google_analytics: UA-72072834-2

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/dirkfabisch
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/faysvas
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:


